[build]
builder = "nixpacks"
# Increase build timeout if needed (default is 1800 seconds)
# buildTimeout = 3600

[deploy]
startCommand = "python dashbord_blur.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10


